### ISSUE TITLE
Add a field that shows the boot session like ContextTraceId

### ISSUE THREAD

**Issue by dfirence** [lcostantino/panoptes#2]
It should recognize the OS boot session from local cache, instead of assigning ContextTraceId based on program start

**Comment by lcostantino** [comment]
Cool! 
currently is possible only thru the JS processor (new fields can be added), but will add the option so it log it natively

**Comment by dfirence** [comment]
Hoping this one gets done.

was thinking if you should check the WinRegistry for last-boot and compare current state?

**Comment by lcostantino** [comment]
Each event now includes a SessionID

 "Panoptes": {
        "SessionId": "89b76852-97e4-4f9b-baf6-7d71d7e5d6b8"
    },
